#Even name
name: on_push

#When the event should run

on:
  push:
    branch:
      - "**" # this will run on all branches, must be quoted to be handled by github

# what jobs to execute

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - uses: actions/checkout@v2
      #install java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      # Run: mvn test
      - name: Run test with maven
        working-directory: webdriver_java
        run: mvn test
        # Handle remote server chromedriver