#Even name
name: on_push

#When the event should run

on:
  push:
    branch:
      - "**" # this will run on all branches, must be quoted to be handled by github

# what jobs to execute

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2