#Even name
name: on_push

#When the event should run

on:
  push:
    branch:
      - "**" # this will run on all branches, must be quoted to be handled by github

# what jobs to execute

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - name: Set the start time 
        -run: echo "START_TIME=$(DATE +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      #install java
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 17
      # Run: mvn test
      - name: Run test with maven
        working-directory: webdriver_java
        run: mvn test
      - name: Collect build data
        if: always()
        run: expr $(date +%s) - ${START_TIME}